modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="yes_steve_model"
    type="required"
    versionRange="${ysm_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="ysm_mapping_api"
    type="required"
    versionRange="[0.1.0,)"
    ordering="BEFORE"
    side="CLIENT"

[[mixins]]
    config="ysm_equipment_render_patch.mixins.json"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="${curios_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="draconicevolution"
    type="optional"
    versionRange="${draconic_evolution_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="kaleidoscope_doll"
    type="optional"
    versionRange="${kaleidoscope_doll_version_range}"
    ordering="AFTER"
    side="CLIENT"
